language: node_js
addons:
  mariadb: '10.4'
before_install:
  - npm install express
  - npm install morgan
  - npm install request
  - npm install mysql
  - npm install iamport
  - mysql -e 'CREATE DATABASE IF NOT EXISTS thunder_mart;'